name: env-iffley

channels:
  - conda-forge

dependencies:
  - python=3.9
  - pip

  # Data
  - pandas
  - tabulate

  # Image processing
  - pillow

  # Jupyter Environment
  - papermill
  - autopep8
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean
  - nbresuse
